name: Build addons

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            devcmd_arch: x64
            artifact_suffix: addon64
          - arch: x86
            devcmd_arch: x86
            artifact_suffix: addon32

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup MSVC (${{ matrix.devcmd_arch }})
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.devcmd_arch }}

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release --parallel

      - name: Collect artifacts
        id: collect
        shell: bash
        run: |
          shopt -s nullglob
          mkdir -p artifacts
          shopt -s extglob
          # Find produced addon file(s)
          mapfile -t files < <(ls -1 build/*renodx-*.${{ matrix.artifact_suffix }} 2>/dev/null || true)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No addon files found; listing build dir for debugging:" >&2
            ls -la build || true
            exit 1
          fi
          for f in "${files[@]}"; do
            base=$(basename "$f")
            cp "$f" "artifacts/$base"
          done
          echo "artifact_dir=artifacts" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: renodx-display-commander-${{ matrix.artifact_suffix }}
          path: ${{ steps.collect.outputs.artifact_dir }}/*
          if-no-files-found: error

  release:
    name: Release
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Download build artifacts (x64)
        uses: actions/download-artifact@v4
        with:
          name: renodx-display-commander-addon64
          path: artifacts

      - name: Download build artifacts (x86)
        uses: actions/download-artifact@v4
        with:
          name: renodx-display-commander-addon32
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


